name: Benchmark

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  benchmark:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew :crypto-perf:jmh

      - name: Read file contents
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: "crypto-perf/build/jmh/result.txt"

      - name: Print result
        uses: actions/github-script@v7
        with:
          script: |
            const readFile = ${{ toJSON(steps.read_file.outputs.contents) }};
            
            console.log("readFile");
            console.log(readFile);